### ISSUE TITLE
Support for passing synchronization scopes

### ISSUE THREAD

**Issue by maleadt** [JuliaConcurrent/UnsafeAtomics.jl#17]
Currently, only `LLVM.Internal.atomic_pointermodify` takes a `syncscope` argument; probably all UnsafeAtomics APIs do.

@pxl-th How are you setting custom syncscopes?

**Comment by pxl-th** [comment]
At the moment I'm just setting syncscope to agent for all FP +- atomic ops:
https://github.com/JuliaGPU/AMDGPU.jl/blob/57d8324533209b456e789897c18a10b021afc090/src/AMDGPU.jl#L149

**Comment by vchuravy** [comment]
After #20 we can now do `UnsafeAtomics.modify!(ptr, op, x, ord, UnsafeAtomics.Internal.LLVMSyncScope{:agent}())`
